# action.yml
name: 'Banner_text'
description: 'Show Text Banner'
inputs:
  banner_text: 
    description: 'Enter Text for Banner'
    required: true
    default: 'G-ABLE'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.banner_text }}'

